{
    "hostname": "github.com",
    "pages_hostname": "github.io",
    "build_revision": "0.0.1",
    "project_title": "Maciej Jaskula blog",
    "project_tagline": "front-end developer blog",
    "owner_name": "Maciej Jaskuła",
    "owner_url": "http://matjas.github.io",
    "repository_url": "https://github.com/matjas/matjas.github.io",
    "repository_name": "matjas-blog",
    "language": null,
    "is_user_page": true,
    "is_project_page": false,
    "show_downloads": false,
    "url": "http://matjas.github.io/metadata-example"
}