{
    "versions": {
        "jekyll": "1.5.1",
        "kramdown": "1.3.1",
        "liquid": "2.5.5",
        "maruku": "0.7.0",
        "rdiscount": "2.1.7",
        "redcarpet": "2.3.0",
        "RedCloth": "4.2.9",
        "jemoji": "0.1.0",
        "jekyll-mentions": "0.0.6",
        "jekyll-redirect-from": "0.3.1",
        "jekyll-sitemap": "0.2.0",
        "github-pages": "18",
        "ruby": "2.1.1"
    },
    "hostname": "github.com",
    "pages_hostname": "github.io",
    "build_revision": "0.0.1",
    "project_title": "Maciej Jaskula blog",
    "project_tagline": "front-end developer blog",
    "owner_name": "Maciej Jaskuła",
    "owner_url": "http://matjas.github.io",
    "repository_url": "https://github.com/matjas/matjas.github.io",
    "repository_name": "matjas-blog",
    "language": null,
    "is_user_page": true,
    "is_project_page": false,
    "show_downloads": false,
    "url": "http://matjas.github.io/metadata-example" // (or the CNAME)
}